server:
  port: 1234
spring:
  application:
    name: eurekaClient 
  datasource:   
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?userUnicode=true&characterEncoding=utf8
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

	  
